services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app_network
    command: ["redis-server"]
    restart: unless-stopped


  flask-app:
    build:
      context: ./flask-app  # Make sure this path is correct relative to docker-compose.yml
    ports:
      - "5000:5000"

    depends_on:
      - redis
    networks:
      - app_network
      
    environment:
      - FLASK_APP=app.py
    restart: unless-stopped
  

networks:
  app_network:
    driver: bridge